### ISSUE TITLE
hunt-searchengine-0.3.0.0 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [hunt-framework/hunt#96]
According to http://hydra.cryp.to/build/598151/log/raw, several modules like `Hunt.AnalyzerTests` are missing from the release tarball.

**Comment by alexbiehl** [comment]
Thanks for your report. Preparing a testable tarball just now.

**Comment by chrisreu** [comment]
Hey,

documentation for hunt-server failed to build as well, might be related

http://hackage.haskell.org/package/hunt-server-0.3.0.2/reports/1
http://hackage.haskell.org/package/hunt-server-cli-0.2.0.0/reports/1

<pre>
Warning: Hunt.Index.Schema.Normalize.Date: could not find link destinations for:
    Hunt.Index.Schema.Normalize.Date.Date Hunt.Index.Schema.Normalize.Date.readAnyDateM
Warning: Hunt.Common.BasicTypes: could not find link destinations for:
    Data.Attoparsec.Internal.Types.More
Warning: Hunt.Index.PrefixTreeIndex: could not find link destinations for:
    Hunt.Index.PrefixTreeIndex.UnInt Hunt.Index.PrefixTreeIndex.UnDate
Warning: Hunt.Query.Result: could not find link destinations for:
    Hunt.Query.Result.Terms
Warning: Hunt.Query.Intermediate: could not find link destinations for:
    Hunt.Query.Intermediate.CxRawResults
Warning: Hunt.Query.Processor: could not find link destinations for:
    Hunt.Query.Processor.QueryIndex Hunt.Query.Processor.evalScoredDocs Hunt.Query.Processor.evalUnScoredDocs Hunt.Query.Processor.evalScoredWords Hunt.Query.Processor.evalScoredRawDocs
Warning: Hunt.Interpreter: could not find link destinations for:
    Hunt.Interpreter.execBasicCmd
</pre>

<pre>
Warning: No documentation was generated as this package does not contain a
library. Perhaps you want to use the --executables, --tests or --benchmarks
flags.
</pre>

**Comment by alexbiehl** [comment]
I adjusted hunt-searchengine's cabal file. 

@chrisreu The report for hunt-server looks good. There is no library in hunt-server, so Hackage does not generate documentation for it. 

hunt-server-cli on the other hand seems to have dependency problem which I can't reproduce locally I think. Will investigate that.

**Comment by chrisreu** [comment]
@alexbiehl: So this is fixed?

**Comment by alexbiehl** [comment]
Think so, should be easier to test with `stack test`.
