### ISSUE TITLE
Better overflow detection in normalizeToInt

### ISSUE THREAD

**Issue by alexbiehl** [hunt-framework/hunt#98]
At the moment `normalizeToInt` in ` Hunt.Index.Schema.Normalize.Int` does not handle overflows correctly thus resulting in failed tests. 

A solution would be to read the string as `Integer` and perform bound checking before casting to `Int`.

```
normalizeToInt' :: Text -> Maybe Int
normalizeToInt' t = either (const Nothing) Just $ do
  (n, "") <- T.signed T.decimal t :: Either String (Integer, Text)
  if (n > fromIntegral (maxBound :: Int))
     || (n < fromIntegral (minBound :: Int))
    then Left "overflow"
    else return (fromIntegral n)
```
Is there a not so ugly way?

**Comment by chrisreu** [comment]
I'm okay with that solution for now.
